# We run pre-commit in our CI with our local tasks.
# We should just remove pre-commit.ci
ci: { skip: [pixi-doc, pixi-format-air, pixi-biome-format, pixi-check-typos] }

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
  - repo: local
    hooks:
      - id: pixi-doc
        name: "Run documentation generator through pixi"
        entry: pixi run doc
        language: system
        types_or: [r]
        pass_filenames: false
      - id: pixi-format-air
        name: "Run air format through pixi"
        entry: pixi run fmt-air
        language: system
        types_or: [r]
        pass_filenames: false
      - id: pixi-biome-format
        name: "Run Biome format through pixi"
        entry: pixi run fmt-biome
        language: system
        types_or: [javascript, jsx, ts, tsx, css]
        exclude: "(^|/)package\\.json$"
      - id: pixi-check-typos
        name: "Run typos through pixi"
        entry: pixi run check-typos
        language: system
